from distutils.core import setup
setup(name='horus-dist',
      version='0.1',
      description='HORUS Framework',
      author='Diego Esteves',
      author_email='diegoesteves@gmail.com',
      url='http://dnes85.github.io/horus-models/',
      packages=['src','components','experiments','postagger','resource','sift'],
      package_dir={'src': 'src/',
                   'components': 'src/components/',
                   'experiments': 'src/experiments/',
                   'postagger': 'src/postagger/',
                   'resource': 'src/resource/',
                   'sift': 'src/sift/'},
      )
