SELECT SRI.ID_TERM, TS.TERM, SUM(SRI.NR_FACES), SUM(SRI.NR_LOGOS)
FROM HORUS_SEARCH_RESULT_IMG SRI, HORUS_TERM_SEARCH TS
WHERE TS.ID = SRI.ID_TERM and ID_TERM IN (SELECT ID FROM HORUS_TERM_SEARCH WHERE id_search_type = 2 and TERM IN ('microsoft', 'americanas', 'Diego', 'Esteves', 'Diego Esteves', 'leipzig'))
GROUP BY id_term, 1


select STR.id, TS.term, STR.id_term, STR.result_seq, STR.result_title, STR.result_title_en, STR.result_description, STR.result_description_en, CT.type
from HORUS_SEARCH_RESULT_TEXT STR, HORUS_TEXT_CLASSIFICATION_TYPES CT, HORUS_TERM_SEARCH TS
where CT.id = STR.text_klass and TS.id = STR.id_term

update HORUS_SEARCH_RESULT_TEXT set result_title_en = NULL, result_description_en = NULL 


SELECT DS1.ID_TERM AS ID_TERM_IMG, DS1.TERM, DS1.FACE, DS1.LOGO, DS1.LANDSCAPE, DS2.ID_TERM AS ID_TERM_TEXT, DS2.TYPE, DS2.NR_VOTES FROM
(SELECT SRI.ID_TERM AS ID_TERM, TS.TERM AS TERM, SUM(SRI.NR_FACES) AS FACE, SUM(SRI.NR_LOGOS) AS LOGO, SUM(SRI.NR_landscape) AS LANDSCAPE
FROM HORUS_SEARCH_RESULT_IMG SRI, HORUS_TERM_SEARCH TS
WHERE TS.ID = SRI.ID_TERM AND
      SRI.ID_TERM IN (
	      SELECT ID FROM HORUS_TERM_SEARCH  
		  WHERE TERM IN ('micrsof'))
GROUP BY SRI.ID_TERM) AS DS1,
(SELECT DS.ID_TERM, TS.TERM, CT.TYPE, MAX(DS.TOT) AS NR_VOTES 
FROM HORUS_TERM_SEARCH TS, HORUS_TEXT_CLASSIFICATION_TYPES CT, (
	SELECT ID_TERM, TEXT_KLASS, COUNT(TEXT_KLASS) AS TOT
	FROM HORUS_SEARCH_RESULT_TEXT
	GROUP BY TEXT_KLASS) AS DS
WHERE DS.ID_TERM = TS.ID AND
      CT.ID = DS.TEXT_KLASS AND
      TS.TERM IN ('micrsof')) AS DS2
	